name: Release Automation

on:
  push:
    tags:
      - 'v*' # Triggers on tags starting with 'v'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.V10.11.12}}
          release_name: ${{ github.v10.11.12 }}
          body: "This release was automatically created."
          draft: false
          prerelease: false
