- name: Bcommitizen-action@v1.1.0 # Replace v1.1.0 with the correct version
     with:
       github_token: ${{ump version and generate changelog
  id: bump
  uses secrets.DEMO_TOKEN }}
       changelog_increment_filename: changelog.md
