name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_NAME: xt_vox_python

    steps:
      - name: 🧾 Check out code
        uses: actions/checkout@v3

      - name: 🔢 Set build number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: 🔐 Log in to GHCR using PAT
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: pasupathiak
          password: ${{ secrets.SIMPLE_TOKEN}}

      - name: 🛠️ Build Docker image
        run: |
          IMAGE_TAG=ghcr.io/xyloite-dev/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}
          echo "Building image: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .

      - name: 🚀 Push Docker image
        run: |
          IMAGE_TAG=ghcr.io/xyloite-dev/${{ env.IMAGE_NAME }}:${{ env.BUILD_NUMBER }}
          echo "Pushing image: $IMAGE_TAG"
          docker push $IMAGE_TAG
