name: Docker Image CI XT-VoX-AI-BE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Set build number from GitHub Actions run number
      - name: Set the build number
        run: echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      # Step 3: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.TEST_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 4: Build the Docker image
      - name: Build Docker image XT-VoX-AI-BE
        run: docker build -t ghcr.io/xyloite-dev/xt-vox-ai-be:${{ env.BUILD_NUMBER }} . --no-cache

      # Step 5: Push Docker image to GHCR
      - name: Push Docker image XT-VoX-AI-BE
        run: docker push ghcr.io/xyloite-dev/xt-vox-ai-be:${{ env.BUILD_NUMBER }}
