name: Build and Push Docker Image with Version

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

permissions:
  contents: write  # Needed for git tag push

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git environment
        run: |
          git fetch --prune --unshallow --tags
      - name: Determine Version
        id: version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          MAJOR=$(echo $LAST_TAG | cut -d '.' -f1 | sed 's/v//')
          MINOR=$(echo $LAST_TAG | cut -d '.' -f2)
          PATCH=$(echo $LAST_TAG | cut -d '.' -f3)
          
          PATCH=$((PATCH + 1))
          
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # ✅ FIXED
          password: ${{ secrets.SIMPLE_TOKEN }}  # ✅ Use a PAT if you get permission denied

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/pasupathiak/xt_vox_python:${{ env.VERSION }}  # ✅ FIXED
          docker build -t $IMAGE .
      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/pasupathiak/xt_vox_python:${{ env.VERSION }}  # ✅ FIXED
          docker push $IMAGE
      - name: Create Git tag for version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
