name: Build and Release Docker Image

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write  # Needed for git tag push

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git environment
        run: |
          git fetch --prune --unshallow --tags

      - name: Determine Version
        id: set-version
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          MAJOR=$(echo $LAST_TAG | cut -d '.' -f1 | sed 's/v//')
          MINOR=$(echo $LAST_TAG | cut -d '.' -f2)
          PATCH=$(echo $LAST_TAG | cut -d '.' -f3)
          PATCH=$((PATCH + 1))
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$NEW_VERSION"

  build-and-push:
    needs: determine-version
    uses: ./.github/workflows/docker-build-push.yml
    with:
      version: ${{ needs.determine-version.outputs.version }}

  release-project:
    needs: [determine-version, build-and-push]
    uses: ./.github/workflows/release-create.yml
    with:
      version: ${{ needs.determine-version.outputs.version }}
