name: Build and Push Docker Images (v1 and v2)

on:
  workflow_dispatch:  # Manual trigger for testing, change to `push:` if needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: xt_vox_python
      VERSION_1: v1
      VERSION_2: v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SIMPLE_TOKEN }}  # or use your own PAT in `secrets.SIMPLE_TOKEN`

      - name: Build Docker image
        run: |
          IMAGE_BASE=ghcr.io/${{ pasupathiak }}/${{ env.IMAGE_NAME }}
          docker build -t $IMAGE_BASE:build-temp .

      - name: Tag and Push v1 and v2
        run: |
          IMAGE_BASE=ghcr.io/${{ pasupathiak }}/${{ env.IMAGE_NAME }}

          # Tagging
          docker tag $IMAGE_BASE:build-temp $IMAGE_BASE:${{ env.VERSION_1 }}
          docker tag $IMAGE_BASE:build-temp $IMAGE_BASE:${{ env.VERSION_2 }}

          # Push both tags
          docker push $IMAGE_BASE:${{ env.VERSION_1 }}
          docker push $IMAGE_BASE:${{ env.VERSION_2 }}
