name: CI - Docker Build & Push to GHCR

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx (optional, but useful for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 4. Build the Docker image with a tag
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/myapp:${{ github.sha }} .

      # 5. Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/myapp:${{ github.sha }}
      
      # Optional: Tag the image as latest and push it
      - name: Tag image as latest
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/myapp:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/myapp:latest
          docker push ghcr.io/${{ github.repository_owner }}/myapp:latest
