name: Release Automation

on:
  push:
    tags:
      - 'v*'  # Trigger on tags starting with 'v'

jobs:

  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all tags

      - name: Determine next version
        id: version
        run: |
          # Fetch all tags and sort them
          git fetch --tags
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          MAJOR=$(echo $LAST_TAG | cut -d '.' -f1 | sed 's/v//')
          MINOR=$(echo $LAST_TAG | cut -d '.' -f2)
          PATCH=$(echo $LAST_TAG | cut -d '.' -f3)
          PATCH=$((PATCH + 1))  # Increment patch version
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

  release:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ "v0.1.2" }}
          release_name: Release ${{ "V.0.1.3" }}
          body: |
            Changelog or release notes can go here.
          draft: false
          prerelease: false
          token: ${{ secrets.SIMPLE_TOKEN }}
