
name: helm deployment in server
stages:
  - build
  - test
  - package
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  HELM_RELEASE: my-python-app
  KUBE_NAMESPACE: default

build:
  stage: build
  script:
    - docker build -t registry.example.com/my-python-app:$IMAGE_TAG .
    - docker push registry.example.com/my-python-app:$IMAGE_TAG

test:
  stage: test
  script:
    - pytest tests/

package_helm_chart:
  stage: package
  script:
    - helm lint ./helm/my-python-app
    - helm package ./helm/my-python-app --version $CI_COMMIT_TAG
    - helm repo index ./helm/packages --url https://charts.example.com/
    - # Push Helm chart to repo (e.g., GitLab Package Registry or Helm repo)

deploy_dev:
  stage: deploy
  environment: development
  script:
    - helm upgrade --install $HELM_RELEASE ./helm/my-python-app \
      --namespace $KUBE_NAMESPACE \
      --set image.repository=registry.example.com/my-python-app \
      --set image.tag=$IMAGE_TAG
  only:
    - develop

deploy_prod:
  stage: deploy
  environment: production
  when: manual
  script:
    - helm upgrade --install $HELM_RELEASE ./helm/my-python-app \
      --namespace $KUBE_NAMESPACE \
      --set image.repository=registry.example.com/my-python-app \
      --set image.tag=$IMAGE_TAG
  only:
    - main
