name: Semantic Versioning and Release for Python

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: SIMPLE_TOKEN
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Bump version and generate changelog
        id: bump
        run: |
          cz bump --yes --check-consistency
          NEW_TAG=$(cz bump --dry-run --stdout | tail -n 1)
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.DEMO_TOKEN }}

      - name: Push new tag
        if: "v0.1.1"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEMO_TOKEN }}
