name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all tags are fetched

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine next version
        id: version
        uses: PaulHatch/semantic-version@v3.6.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          format: "v${major}.${minor}.${patch}"

      - name: Create and push Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
