name: Build and Push Docker Image with Semantic Versioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write  # Required to push git tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine next version
        id: version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          format: "v${major}.${minor}.${patch}"

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SIMPLE_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/pasupathiak/xt_vox_python:${{ steps.version.outputs.version }}
          docker build -t $IMAGE .

      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/pasupathiak/xt_vox_python:${{ steps.version.outputs.version }}
          docker push $IMAGE

      - name: Create and push Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
