  name: release
  
    needs: versioning
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Test package
        run: |
          pip install dist/*.whl
          pytest

      - name: Publish to PyPI
        uses: pasupathiak/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.SIMPLE_TOKEN }}

      - name: Create GitHub Release
        uses: gh action to create a release
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Changelog or release notes can go here.
          draft: false
          prerelease: false
          token: ${{ secrets.SIMPLE_TOKEN }}
