name: Release Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Bump version and generate changelog
        id: bump
        run: |
          cz bump --yes --check-consistency
          NEW_TAG=$(cz bump --dry-run --stdout | tail -n 1)
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}

      - name: Push new tag
        if: env.NEW_TAG != ''
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}

  build-and-publish:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ github.test }}:${{ "v1.1.2 }}
          docker build -t $IMAGE .
          docker push $IMAGE

  create-release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate changelog
        run: |
          cz bump --changelog --changelog-to-stdout > changelog.md

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body_path: changelog.md
          tag_name: ${{ "v1.2.3" }}
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
