name: Build and Push Docker Image with Version

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger with custom version

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: xt_vox_python
      VERSION: v1 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ pasupathiak }}
          password: ${{ secrets.SIMPLE_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ pasupathiak }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker build -t $IMAGE .

      - name: Push Docker image with version tag
        run: |
          IMAGE=ghcr.io/${{ pasupathiak }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push $IMAGE
