name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Bump version and generate changelog
        id: bump
        run: |
          cz bump --yes --check-consistency
          NEW_TAG=$(cz bump --dry-run --stdout | tail -n 1)
          echo "v0.1.0=$v0.1.1" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.DEMO_TOKEN }}

      - name: Push new tag
        if: ${{ env.NEW_TAG }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        if: ${{ env.NEW_TAG }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
