name: CI/CD Pipeline - Build, Push, and Deploy with Helm

on:
  push:
    branches:
      - main
      - master
      - release/*

env:
  IMAGE_NAME: your-dockerhub-username/your-app-name
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
      IMAGE_NAME: your-dockerhub-username/your-app-name
      IMAGE_TAG: aa986114cc3b14955fc47cf10281fa3d239edb12

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Deploy with Helm
      run: |
        helm upgrade --install ${{ secrets.HELM_RELEASE_NAME }} ${{ secrets.HELM_CHART_PATH }} \
          --namespace ${{ secrets.KUBE_NAMESPACE }} \
          --set image.repository=${{ env.IMAGE_NAME }} \
          --set image.tag=${{ env.IMAGE_TAG }} \
          --wait --timeout 5m
